In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (3.7.1)
Requirement already satisfied: cycler>=0.10 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: numpy>=1.20 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.24.2)
Requirement already satisfied: packaging>=20.0 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (23.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.0.7)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (4.39.3)
Requirement already satisfied: six>=1.5 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (1.7.5)
Requirement already satisfied: scipy in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.10.1)
Requirement already satisfied: numpy in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.24.2)

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.1.0)

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\quentin\appdata\local\programs\python\python310\lib\site-packages (1.24.2)

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from numpy import absolute
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from xgboost import XGBRegressor

In [7]:
df = pd.read_csv("video_games_sales.csv")

In [8]:
df

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

transformé le name en valeur => (mot clé)
Package -> word cloud (compter les fréquences de mot dans la liste)
combien de genre / publisher / platform

In [9]:
df.describe()

,rank,year,na_sales,eu_sales,jp_sales,other_sales,global_sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [10]:
# grouper par noms et calculer la moyenne des valeurs
df.groupby(["genre"]).agg({"eu_sales": "sum"}).reset_index()

           genre  eu_sales
0         Action    525.00
1      Adventure     64.13
2       Fighting    101.32
3           Misc    215.98
4       Platform    201.63
5         Puzzle     50.78
6         Racing    238.39
7   Role-Playing    188.06
8        Shooter    313.27
9     Simulation    113.38
10        Sports    376.85
11      Strategy     45.34

In [11]:
(df.groupby(["publisher"]).count().sort_values("rank", ascending=False)['rank']).nlargest(50)

publisher
Electronic Arts                           1351
Activision                                 975
Namco Bandai Games                         932
Ubisoft                                    921
Konami Digital Entertainment               832
THQ                                        715
Nintendo                                   703
Sony Computer Entertainment                683
Sega                                       639
Take-Two Interactive                       413
Capcom                                     381
Atari                                      363
Tecmo Koei                                 338
Square Enix                                233
Warner Bros. Interactive Entertainment     232
Disney Interactive Studios                 218
Unknown                                    203
Eidos Interactive                          198
Midway Games                               198
505 Games                                  192
Microsoft Game Studios                     189
Acclaim Entertainment                      184
D3Publisher                                184
Vivendi Games                              164
Codemasters                                152
Idea Factory                               129
Deep Silver                                122
Nippon Ichi Software                       105
Zoo Digital Publishing                     104
Majesco Entertainment                       92
LucasArts                                   90
Rising Star Games                           86
Hudson Soft                                 81
Banpresto                                   73
Bethesda Softworks                          71
Crave Entertainment                         71
Atlus                                       67
Virgin Interactive                          62
Infogrames                                  62
Ignition Entertainment                      61
5pb                                         61
Focus Home Interactive                      58
Marvelous Interactive                       56
Empire Interactive                          52
SquareSoft                                  52
Kadokawa Shoten                             50
Destineer                                   45
GT Interactive                              45
DTP Entertainment                           45
Alchemist                                   43
Name: rank, dtype: int64

In [12]:
# grouper par année et genre et calculer les ventes totales
df_grouped = df.groupby(["year", "genre"])["eu_sales"].sum().reset_index()

# trouver l'index du genre le plus vendu pour chaque année
idx = df_grouped.groupby("year")["eu_sales"].idxmax()

# afficher le dataframe trié par année et le genre le plus vendu
print(df_grouped.loc[idx].sort_values("year"))

       year         genre  eu_sales
3    1980.0       Shooter      0.43
5    1981.0        Action      0.81
15   1982.0        Puzzle      0.58
22   1983.0      Platform      0.43
31   1984.0       Shooter      0.85
35   1985.0      Platform      3.77
40   1986.0        Action      1.66
48   1987.0      Fighting      0.65
54   1988.0      Platform      4.99
64   1989.0        Puzzle      3.61
69   1990.0      Platform      3.99
79   1991.0      Platform      1.19
88   1992.0     Adventure      2.81
103  1993.0      Platform      3.16
115  1994.0      Platform      5.73
127  1995.0      Platform      3.22
142  1996.0  Role-Playing     11.04
153  1997.0        Racing     10.82
159  1998.0        Action     11.90
178  1999.0  Role-Playing     11.17
183  2000.0        Action     10.84
195  2001.0        Action     19.25
207  2002.0        Action     27.01
219  2003.0        Action     20.88
238  2004.0  Role-Playing     16.73
243  2005.0        Action     21.95
265  2006.0        Sports     40.20
277  2007.0        Sports     26.54
279  2008.0        Action     39.49
301  2009.0        Sports     42.17
303  2010.0        Action     35.75
315  2011.0        Action     41.04
327  2012.0        Action     42.78
339  2013.0        Action     45.21
351  2014.0        Action     40.48
363  2015.0        Action     24.65
382  2016.0       Shooter      7.70
386  2017.0        Action      0.00
388  2020.0    Simulation      0.00

-------------------------------------
# /!\ a supprimer /!\

- Nettoyer la data
- LabelEncoder
- OneHotEncoder -> créer des categories (collones) -> a regarder -> A PRENDRE
- split train test
- Xgboost Regression xgb(x.train, y.train) / xgb.predict(x.test, y.test)

- db.apply(callback, axis = 1) == js.map(callback)


# /!\ a supprimer /!\

-----------------------------------

In [13]:
df_filter = df.dropna()
df = df_filter[df_filter.publisher != 'Unknown']
df

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

##### recupérer les 50 éditeurs qui ont publié dans liste

In [14]:
df_publisher = (df.groupby(["publisher"]).count().sort_values("rank", ascending=False)['rank']).nlargest(50)
df_publisher

publisher
Electronic Arts                           1339
Activision                                 966
Namco Bandai Games                         928
Ubisoft                                    918
Konami Digital Entertainment               823
THQ                                        712
Nintendo                                   696
Sony Computer Entertainment                682
Sega                                       632
Take-Two Interactive                       412
Capcom                                     376
Atari                                      347
Tecmo Koei                                 338
Square Enix                                231
Warner Bros. Interactive Entertainment     217
Disney Interactive Studios                 214
Midway Games                               196
Eidos Interactive                          196
505 Games                                  192
Microsoft Game Studios                     189
Acclaim Entertainment                      184
D3Publisher                                183
Vivendi Games                              161
Codemasters                                150
Idea Factory                               128
Deep Silver                                121
Zoo Digital Publishing                     104
Nippon Ichi Software                       104
Majesco Entertainment                       90
LucasArts                                   89
Rising Star Games                           85
Hudson Soft                                 81
Banpresto                                   73
Crave Entertainment                         71
Bethesda Softworks                          69
Atlus                                       67
Virgin Interactive                          62
Infogrames                                  61
5pb                                         61
Ignition Entertainment                      59
Marvelous Interactive                       56
Focus Home Interactive                      56
SquareSoft                                  52
Empire Interactive                          51
Kadokawa Shoten                             50
Destineer                                   45
GT Interactive                              45
DTP Entertainment                           44
Alchemist                                   43
MTV Games                                   40
Name: rank, dtype: int64

In [15]:
df_publisher_top = df["publisher"].value_counts().head(50).index
df_publisher_top

Index(['Electronic Arts', 'Activision', 'Namco Bandai Games', 'Ubisoft',
       'Konami Digital Entertainment', 'THQ', 'Nintendo',
       'Sony Computer Entertainment', 'Sega', 'Take-Two Interactive', 'Capcom',
       'Atari', 'Tecmo Koei', 'Square Enix',
       'Warner Bros. Interactive Entertainment', 'Disney Interactive Studios',
       'Midway Games', 'Eidos Interactive', '505 Games',
       'Microsoft Game Studios', 'Acclaim Entertainment', 'D3Publisher',
       'Vivendi Games', 'Codemasters', 'Idea Factory', 'Deep Silver',
       'Zoo Digital Publishing', 'Nippon Ichi Software',
       'Majesco Entertainment', 'LucasArts', 'Rising Star Games',
       'Hudson Soft', 'Banpresto', 'Crave Entertainment', 'Bethesda Softworks',
       'Atlus', 'Virgin Interactive', '5pb', 'Infogrames',
       'Ignition Entertainment', 'Marvelous Interactive',
       'Focus Home Interactive', 'SquareSoft', 'Empire Interactive',
       'Kadokawa Shoten', 'Destineer', 'GT Interactive', 'DTP Entertainment',
       'Alchemist', 'MTV Games'],
      dtype='object')

In [16]:
def replace_publiser(x):
    if x["publisher"] in df_publisher_top :
        return x["publisher"]
    else : 
        return "Other"
df["publisher"] = df.apply(replace_publiser, axis = 1)

C:\Users\Quentin\AppData\Local\Temp\ipykernel_16852\1186362189.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["publisher"] = df.apply(replace_publiser, axis = 1)

In [17]:
df

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Other,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,Other,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Other,0.01,0.00,0.00,0.00,0.01

In [18]:
enc = OneHotEncoder(drop ='if_binary')
data_enc = enc.fit_transform(df["genre"].values.reshape(-1, 1)).toarray()
column_enc = enc.get_feature_names_out(["genre"])
one_hot_genre = pd.DataFrame(data_enc, columns =column_enc, index = df.index )

In [19]:
enc = OneHotEncoder(drop ='if_binary')
data_enc = enc.fit_transform(df["publisher"].values.reshape(-1, 1)).toarray()
column_enc = enc.get_feature_names_out(["publisher"])
one_hot_publisher = pd.DataFrame(data_enc, columns =column_enc, index = df.index )

In [20]:
enc = OneHotEncoder(drop ='if_binary')
data_enc = enc.fit_transform(df["platform"].values.reshape(-1, 1)).toarray()
column_enc = enc.get_feature_names_out(["platform"])
one_hot_platform = pd.DataFrame(data_enc, columns =column_enc, index = df.index )

In [21]:
#df_filter_not_unknown[column_enc] = one_hot_genre

df_new_array = pd.concat([df, one_hot_platform, one_hot_genre, one_hot_publisher], axis = 1)
df_new_array

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,...,publisher_Square Enix,publisher_SquareSoft,publisher_THQ,publisher_Take-Two Interactive,publisher_Tecmo Koei,publisher_Ubisoft,publisher_Virgin Interactive,publisher_Vivendi Games,publisher_Warner Bros. Interactive Entertainment,publisher_Zoo Digital Publishing
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Other,0.01,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16596,16599,Know How 2,DS,2010.0,Puzzle,Other,0.00,0.01,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Other,0.01,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
(df.groupby(["publisher"]).count().sort_values("rank", ascending=False)['rank']).nlargest(50)

publisher
Other                                     3102
Electronic Arts                           1339
Activision                                 966
Namco Bandai Games                         928
Ubisoft                                    918
Konami Digital Entertainment               823
THQ                                        712
Nintendo                                   696
Sony Computer Entertainment                682
Sega                                       632
Take-Two Interactive                       412
Capcom                                     376
Atari                                      347
Tecmo Koei                                 338
Square Enix                                231
Warner Bros. Interactive Entertainment     217
Disney Interactive Studios                 214
Midway Games                               196
Eidos Interactive                          196
505 Games                                  192
Microsoft Game Studios                     189
Acclaim Entertainment                      184
D3Publisher                                183
Vivendi Games                              161
Codemasters                                150
Idea Factory                               128
Deep Silver                                121
Nippon Ichi Software                       104
Zoo Digital Publishing                     104
Majesco Entertainment                       90
LucasArts                                   89
Rising Star Games                           85
Hudson Soft                                 81
Banpresto                                   73
Crave Entertainment                         71
Bethesda Softworks                          69
Atlus                                       67
Virgin Interactive                          62
Infogrames                                  61
5pb                                         61
Ignition Entertainment                      59
Marvelous Interactive                       56
Focus Home Interactive                      56
SquareSoft                                  52
Empire Interactive                          51
Kadokawa Shoten                             50
Destineer                                   45
GT Interactive                              45
DTP Entertainment                           44
Alchemist                                   43
Name: rank, dtype: int64

In [23]:
df_new_array

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,...,publisher_Square Enix,publisher_SquareSoft,publisher_THQ,publisher_Take-Two Interactive,publisher_Tecmo Koei,publisher_Ubisoft,publisher_Virgin Interactive,publisher_Vivendi Games,publisher_Warner Bros. Interactive Entertainment,publisher_Zoo Digital Publishing
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Other,0.01,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16596,16599,Know How 2,DS,2010.0,Puzzle,Other,0.00,0.01,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Other,0.01,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
y_df = df_new_array["eu_sales"]
y_df

0        29.02
1         3.58
2        12.88
3        11.01
4         8.89
         ...
16593     0.00
16594     0.00
16595     0.00
16596     0.01
16597     0.00
Name: eu_sales, Length: 16191, dtype: float64

In [25]:
x_df = df_new_array.drop(['rank','name','platform','genre','publisher'], axis = 1)
x_df

,year,na_sales,eu_sales,jp_sales,other_sales,global_sales,platform_2600,platform_3DO,platform_3DS,platform_DC,...,publisher_Square Enix,publisher_SquareSoft,publisher_THQ,publisher_Take-Two Interactive,publisher_Tecmo Koei,publisher_Ubisoft,publisher_Virgin Interactive,publisher_Vivendi Games,publisher_Warner Bros. Interactive Entertainment,publisher_Zoo Digital Publishing
0,2006.0,41.49,29.02,3.77,8.46,82.74,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1985.0,29.08,3.58,6.81,0.77,40.24,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2008.0,15.85,12.88,3.79,3.31,35.82,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2009.0,15.75,11.01,3.28,2.96,33.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1996.0,11.27,8.89,10.22,1.00,31.37,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,2002.0,0.01,0.00,0.00,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16594,2003.0,0.01,0.00,0.00,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16595,2008.0,0.00,0.00,0.00,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16596,2010.0,0.00,0.01,0.00,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16597,2003.0,0.01,0.00,0.00,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
X_train, X_test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.3, random_state=123)

In [27]:
X_train

,year,na_sales,eu_sales,jp_sales,other_sales,global_sales,platform_2600,platform_3DO,platform_3DS,platform_DC,...,publisher_Square Enix,publisher_SquareSoft,publisher_THQ,publisher_Take-Two Interactive,publisher_Tecmo Koei,publisher_Ubisoft,publisher_Virgin Interactive,publisher_Vivendi Games,publisher_Warner Bros. Interactive Entertainment,publisher_Zoo Digital Publishing
7605,2010.0,0.10,0.04,0.04,0.02,0.20,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7817,2010.0,0.17,0.01,0.00,0.01,0.19,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3340,2005.0,0.42,0.16,0.00,0.02,0.60,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16031,2009.0,0.00,0.00,0.01,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4366,2008.0,0.19,0.13,0.07,0.06,0.45,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12512,1998.0,0.05,0.01,0.00,0.00,0.06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1360,1994.0,0.57,0.12,0.71,0.02,1.42,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11888,2004.0,0.04,0.03,0.00,0.01,0.07,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16107,2014.0,0.00,0.00,0.01,0.00,0.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3642,2009.0,0.30,0.17,0.00,0.07,0.55,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
y_test

2959     0.09
1218     0.41
5092     0.00
11477    0.00
7921     0.08
         ...
2805     0.16
9119     0.03
15654    0.01
9780     0.03
723      0.61
Name: eu_sales, Length: 4858, dtype: float64

In [29]:
model = XGBRegressor()
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [30]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X_test, y_test, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
# force scores to be positive
scores = absolute(scores)
print('Mean MAE: %.3f (%.3f)' % (scores.mean(), scores.std()) )

Mean MAE: 0.002 (0.001)

In [31]:
model.predict(X_train.head(1))

array([0.03993832], dtype=float32)

In [34]:
model.save_model("model.json")